### ISSUE TITLE
Make it clearer when a challenge should be done locally vs remotely

### ISSUE THREAD

**Issue by bkonicek** [FixTheOps/fixtheops-public#3]
**Is your feature request related to a problem? Please describe.**
The first challenge that I picked to try (`Root?! Someone to blame - 1`), I spent a while trying to figure out how to launch an environment in order to complete it. I only realized after looking at a few other challenges that I was supposed to run it on my own machine and didn't need a remote environment to do it.

**Describe the solution you'd like**
Clearer instructions for challenges like this that they should be run on our own machines.

**Comment by bkonicek** [comment]
I just noticed that the main challenges view has an icon for which challenges start a remote cluster, so maybe this isn't needed after all!

**Comment by Lp-Francois** [comment]
Hey @bkonicek thanks for the info :) 

How would you imagine a better visualisation to indicate that you need to run it on your machine? Or would the kubernetes icon on the main page be enough?

<img width="1191" alt="Screenshot 2023-05-18 at 22 10 23" src="https://github.com/FixTheOps/fixtheops-public/assets/32224751/69a77078-3b72-4904-b943-f4dedf35e0bf">

**Comment by bkonicek** [comment]
I think the icon is probably enough. The only other improvement for this I can think of would be something like an additional icon for a local machine challenge (maybe a laptop?), and including the environment icons somewhere in the description page for each challenge.

**Comment by Lp-Francois** [comment]
Thanks I added it to the backlog, will be implemented soon :)

**Comment by Lp-Francois** [comment]
FYI I added the logo when it spawns a cluster on the challenge page :)

For now I won't add a "local" logo for other types, I need to think how to do it nicely to not confuse the user (as you connect to the K8s from local it might seem weird to have a logo local and a logo k8s).

<img width="928" alt="Screenshot 2023-05-23 at 00 10 02" src="https://github.com/FixTheOps/fixtheops-public/assets/32224751/700389b9-5f47-4679-9166-d0e3d5eba8b2">

**Comment by bkonicek** [comment]
Awesome, sounds good!
