### ISSUE TITLE
Apply more hint but the next hint will decrease the point

### ISSUE THREAD

**Issue by muhammad-asn** [FixTheOps/fixtheops-public#4]
If feasible and in line with the objectives of the Fixtheops team, it might be beneficial to provide additional hints that gradually reduce the points.

Example:
1. Problem X
    - Hint 1 --> - 0 points
    - Hint 2 --> - 10 points
    - Hint 3 --> - 30 points

**Comment by Lp-Francois** [comment]
Hello @muhammad-asn 👋!

Thanks for giving feedback, I've thought about something similar, like a hint button but it becomes quite complicated code-wise and I prefer to focus on pushing more challenges for now :)

I will definitely add it to the backlog though 👍 

And as a side-note: there is a #help channel in the discord if you struggle with one challenge, feel free to post something there if you feel stuck :)

**Comment by Lp-Francois** [comment]
I will push in the backlog the hints feature, but won't remove any points on hint reveal, to develop the feature faster :)
