### ISSUE TITLE
[BUG] Solving a problem requires "Check" to be submitted twice

### ISSUE THREAD

**Issue by Luke-McMahon** [FixTheOps/fixtheops-public#5]
**Describe the bug**
When submitting answers for certain challenges that don't require cloud services, such as "someone-to-blame-1" and "logs-exploration-1," I need to submit my answer twice. On the first submission, I receive an error message prompting me to make changes and try again. However, upon resubmitting the exact same answer, the response acknowledges that I have already completed the challenge previously but marks it as complete.

**Time of the bug**
2023-05-29 10:00-11:00 AEDT (GMT+10)

**To Reproduce**
1.     Go to the challenges section.
2.     Navigate to the "someone to blame - 1" challenge.
3.     Enter the correct answer.
4.     Click on the "Submit" button.
5.     Encounter an error message.
6.     Without changing the answer, click on the "Submit" button again.
7.     Observe that the submission is marked as successful.

**Expected behavior**

**Screenshots**
I expected to see the success message on the first submission when my answer is correct. There should be no error message prompting me to make changes and try again.

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.5.1
 - Browser: Firefox
 - Version: 113.0.2 (64-bit)

**Comment by Lp-Francois** [comment]
Hello 👋 @Luke-McMahon,

Thanks for submitting the bug, I will have a look later today

**Comment by Lp-Francois** [comment]
Hey @Luke-McMahon, FYI I managed to reproduce the bug, but it doesn't happen every time 🤔

I'll let you know when it is fixed :)

**Comment by Lp-Francois** [comment]
Bug found and fixed 🐛 
The fix is currently live and tested manually ✅ 

The impacted challenges by this bug were:

- Root?! Someone to blame - 1
- Logs exploration - 1
- Secrets restoration - 1
- Doppler super secure

Sorry for the inconvenience and thanks for the bug report 💚 💚 💚 

PS: (I added a cool badge to your profile too 😉)
