### ISSUE TITLE
[BUG] Challenge 13: Table name change

### ISSUE THREAD

**Issue by nsakkos** [FixTheOps/fixtheops-public#6]
In challenge 13 "Payroll Panic: A Recovery Mission - 1", according to the prompt the data is supposed to be in the "payroll" table. However, there is only one table called "users" in the database. Maybe it could be changed in one of the two places?

Excellent job, the website looks great and the challenges are very fun  :100:

**Comment by Lp-Francois** [comment]
Great catch, I will update the challenge :)
Thanks for the feedback 🙏
